# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"


gem "hoe-yard", ">=0.1.2", :group => [:development, :test]
gem "hoe-bundler", ">=1.1", :group => [:development, :test]
gem "hoe-gemspec", ">=1.0", :group => [:development, :test]
gem "hoe-git", ">=1.4", :group => [:development, :test]
gem "minitest", "~>2.2.2", :group => [:development, :test]
gem "codeclimate-test-reporter", ">=0.4", :group => [:development, :test]
gem "hoe", "~>3.13", :group => [:development, :test]

# vim: syntax=ruby
